[package]
name = "refindgen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
